// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clui/completion.proto

package clui

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CompletionEntry struct {
	ActualInput          string   `protobuf:"bytes,1,opt,name=actual_input,json=actualInput,proto3" json:"actual_input,omitempty"`
	Suggestion           string   `protobuf:"bytes,2,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Level                int64    `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	ShouldInput          bool     `protobuf:"varint,5,opt,name=should_input,json=shouldInput,proto3" json:"should_input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompletionEntry) Reset()         { *m = CompletionEntry{} }
func (m *CompletionEntry) String() string { return proto.CompactTextString(m) }
func (*CompletionEntry) ProtoMessage()    {}
func (*CompletionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a495dca42e8a91c1, []int{0}
}

func (m *CompletionEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompletionEntry.Unmarshal(m, b)
}
func (m *CompletionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompletionEntry.Marshal(b, m, deterministic)
}
func (m *CompletionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompletionEntry.Merge(m, src)
}
func (m *CompletionEntry) XXX_Size() int {
	return xxx_messageInfo_CompletionEntry.Size(m)
}
func (m *CompletionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CompletionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CompletionEntry proto.InternalMessageInfo

func (m *CompletionEntry) GetActualInput() string {
	if m != nil {
		return m.ActualInput
	}
	return ""
}

func (m *CompletionEntry) GetSuggestion() string {
	if m != nil {
		return m.Suggestion
	}
	return ""
}

func (m *CompletionEntry) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CompletionEntry) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *CompletionEntry) GetShouldInput() bool {
	if m != nil {
		return m.ShouldInput
	}
	return false
}

type CompletionInfo struct {
	Entries              []*CompletionEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Col                  int64              `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Line                 int64              `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	BufferLength         int64              `protobuf:"varint,5,opt,name=buffer_length,json=bufferLength,proto3" json:"buffer_length,omitempty"`
	IsFirst              bool               `protobuf:"varint,6,opt,name=is_first,json=isFirst,proto3" json:"is_first,omitempty"`
	IsEmpty              bool               `protobuf:"varint,7,opt,name=is_empty,json=isEmpty,proto3" json:"is_empty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CompletionInfo) Reset()         { *m = CompletionInfo{} }
func (m *CompletionInfo) String() string { return proto.CompactTextString(m) }
func (*CompletionInfo) ProtoMessage()    {}
func (*CompletionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a495dca42e8a91c1, []int{1}
}

func (m *CompletionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompletionInfo.Unmarshal(m, b)
}
func (m *CompletionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompletionInfo.Marshal(b, m, deterministic)
}
func (m *CompletionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompletionInfo.Merge(m, src)
}
func (m *CompletionInfo) XXX_Size() int {
	return xxx_messageInfo_CompletionInfo.Size(m)
}
func (m *CompletionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CompletionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CompletionInfo proto.InternalMessageInfo

func (m *CompletionInfo) GetEntries() []*CompletionEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *CompletionInfo) GetCol() int64 {
	if m != nil {
		return m.Col
	}
	return 0
}

func (m *CompletionInfo) GetLine() int64 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *CompletionInfo) GetBufferLength() int64 {
	if m != nil {
		return m.BufferLength
	}
	return 0
}

func (m *CompletionInfo) GetIsFirst() bool {
	if m != nil {
		return m.IsFirst
	}
	return false
}

func (m *CompletionInfo) GetIsEmpty() bool {
	if m != nil {
		return m.IsEmpty
	}
	return false
}

func init() {
	proto.RegisterType((*CompletionEntry)(nil), "clui.CompletionEntry")
	proto.RegisterType((*CompletionInfo)(nil), "clui.CompletionInfo")
}

func init() { proto.RegisterFile("clui/completion.proto", fileDescriptor_a495dca42e8a91c1) }

var fileDescriptor_a495dca42e8a91c1 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcb, 0x4e, 0xeb, 0x30,
	0x10, 0x86, 0xe5, 0xe3, 0xde, 0x8e, 0xd3, 0x73, 0x91, 0x45, 0xa5, 0xb0, 0x41, 0xa1, 0x6c, 0xb2,
	0x21, 0x16, 0x74, 0xc3, 0x1a, 0x54, 0xa4, 0x4a, 0xac, 0xbc, 0x64, 0x53, 0xb5, 0xee, 0x24, 0xb1,
	0x70, 0xec, 0x28, 0xb6, 0x11, 0x7d, 0x2a, 0xde, 0x81, 0x27, 0x43, 0x76, 0x5a, 0xa8, 0xd8, 0xcd,
	0x7c, 0x33, 0xc9, 0xff, 0x8d, 0x4c, 0x66, 0x42, 0x79, 0xc9, 0x84, 0x69, 0x5a, 0x05, 0x4e, 0x1a,
	0x5d, 0xb4, 0x9d, 0x71, 0x86, 0x0e, 0x02, 0x9e, 0xbf, 0x23, 0xf2, 0xef, 0xe1, 0x6b, 0xb4, 0xd4,
	0xae, 0xdb, 0xd3, 0x4b, 0x32, 0xdd, 0x08, 0xe7, 0x37, 0x6a, 0x2d, 0x75, 0xeb, 0x5d, 0x8a, 0x32,
	0x94, 0xff, 0xe6, 0x49, 0xcf, 0x56, 0x01, 0xd1, 0x0b, 0x42, 0xac, 0xaf, 0x2a, 0xb0, 0xe1, 0xab,
	0xf4, 0x57, 0x5c, 0x38, 0x21, 0x34, 0x23, 0xc9, 0x0e, 0xac, 0xe8, 0x64, 0x1b, 0x17, 0x70, 0xff,
	0x87, 0x13, 0x44, 0xcf, 0xc8, 0x50, 0xc1, 0x2b, 0xa8, 0x74, 0x90, 0xa1, 0x1c, 0xf3, 0xbe, 0x09,
	0xd1, 0xb6, 0x36, 0x5e, 0xed, 0x0e, 0xd1, 0xc3, 0x0c, 0xe5, 0x13, 0x9e, 0xf4, 0x2c, 0x46, 0xcf,
	0x3f, 0x10, 0xf9, 0xfb, 0x6d, 0xbc, 0xd2, 0xa5, 0xa1, 0x8c, 0x8c, 0x41, 0xbb, 0x4e, 0x82, 0x4d,
	0x51, 0x86, 0xf3, 0xe4, 0x76, 0x56, 0x84, 0xe3, 0x8a, 0x1f, 0x87, 0xf1, 0xe3, 0x16, 0xfd, 0x4f,
	0xb0, 0x30, 0x2a, 0x7a, 0x63, 0x1e, 0x4a, 0x4a, 0xc9, 0x40, 0x49, 0x0d, 0xd1, 0x14, 0xf3, 0x58,
	0xd3, 0x2b, 0xf2, 0x67, 0xeb, 0xcb, 0x12, 0xba, 0xb5, 0x02, 0x5d, 0xb9, 0x3a, 0xda, 0x60, 0x3e,
	0xed, 0xe1, 0x53, 0x64, 0xf4, 0x9c, 0x4c, 0xa4, 0x5d, 0x97, 0xb2, 0xb3, 0x2e, 0x1d, 0x45, 0xdb,
	0xb1, 0xb4, 0x8f, 0xa1, 0x3d, 0x8c, 0xa0, 0x69, 0xdd, 0x3e, 0x1d, 0x1f, 0x47, 0xcb, 0xd0, 0xde,
	0x2f, 0x9e, 0x6f, 0x2a, 0xe9, 0x6a, 0xbf, 0x2d, 0x84, 0x69, 0x58, 0x23, 0x45, 0xbd, 0x01, 0xa5,
	0x00, 0xee, 0x58, 0x10, 0xbf, 0xd6, 0xf2, 0x8d, 0x55, 0x86, 0xb5, 0x2f, 0x15, 0x8b, 0x8f, 0x15,
	0xe9, 0x76, 0x14, 0xeb, 0xc5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0xef, 0x70, 0x0b, 0xd1,
	0x01, 0x00, 0x00,
}
