// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: clui/completion.proto

package clui

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletionEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActualInput string `protobuf:"bytes,1,opt,name=actual_input,json=actualInput,proto3" json:"actual_input,omitempty"`
	Suggestion  string `protobuf:"bytes,2,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Level       int64  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	ShouldInput bool   `protobuf:"varint,5,opt,name=should_input,json=shouldInput,proto3" json:"should_input,omitempty"`
}

func (x *CompletionEntry) Reset() {
	*x = CompletionEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clui_completion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionEntry) ProtoMessage() {}

func (x *CompletionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_clui_completion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionEntry.ProtoReflect.Descriptor instead.
func (*CompletionEntry) Descriptor() ([]byte, []int) {
	return file_clui_completion_proto_rawDescGZIP(), []int{0}
}

func (x *CompletionEntry) GetActualInput() string {
	if x != nil {
		return x.ActualInput
	}
	return ""
}

func (x *CompletionEntry) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *CompletionEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CompletionEntry) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CompletionEntry) GetShouldInput() bool {
	if x != nil {
		return x.ShouldInput
	}
	return false
}

type CompletionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries      []*CompletionEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Col          int64              `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Line         int64              `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	BufferLength int64              `protobuf:"varint,5,opt,name=buffer_length,json=bufferLength,proto3" json:"buffer_length,omitempty"`
	IsFirst      bool               `protobuf:"varint,6,opt,name=is_first,json=isFirst,proto3" json:"is_first,omitempty"`
	IsEmpty      bool               `protobuf:"varint,7,opt,name=is_empty,json=isEmpty,proto3" json:"is_empty,omitempty"`
}

func (x *CompletionInfo) Reset() {
	*x = CompletionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clui_completion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionInfo) ProtoMessage() {}

func (x *CompletionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clui_completion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionInfo.ProtoReflect.Descriptor instead.
func (*CompletionInfo) Descriptor() ([]byte, []int) {
	return file_clui_completion_proto_rawDescGZIP(), []int{1}
}

func (x *CompletionInfo) GetEntries() []*CompletionEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *CompletionInfo) GetCol() int64 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *CompletionInfo) GetLine() int64 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *CompletionInfo) GetBufferLength() int64 {
	if x != nil {
		return x.BufferLength
	}
	return 0
}

func (x *CompletionInfo) GetIsFirst() bool {
	if x != nil {
		return x.IsFirst
	}
	return false
}

func (x *CompletionInfo) GetIsEmpty() bool {
	if x != nil {
		return x.IsEmpty
	}
	return false
}

type CompletionSourceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Col     int64  `protobuf:"varint,1,opt,name=col,proto3" json:"col,omitempty"`
	Line    int64  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Dir     string `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
	LBuffer string `protobuf:"bytes,4,opt,name=l_buffer,json=lBuffer,proto3" json:"l_buffer,omitempty"`
	RBuffer string `protobuf:"bytes,5,opt,name=r_buffer,json=rBuffer,proto3" json:"r_buffer,omitempty"`
	Buffer  string `protobuf:"bytes,6,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (x *CompletionSourceInfo) Reset() {
	*x = CompletionSourceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clui_completion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletionSourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionSourceInfo) ProtoMessage() {}

func (x *CompletionSourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clui_completion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionSourceInfo.ProtoReflect.Descriptor instead.
func (*CompletionSourceInfo) Descriptor() ([]byte, []int) {
	return file_clui_completion_proto_rawDescGZIP(), []int{2}
}

func (x *CompletionSourceInfo) GetCol() int64 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *CompletionSourceInfo) GetLine() int64 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *CompletionSourceInfo) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *CompletionSourceInfo) GetLBuffer() string {
	if x != nil {
		return x.LBuffer
	}
	return ""
}

func (x *CompletionSourceInfo) GetRBuffer() string {
	if x != nil {
		return x.RBuffer
	}
	return ""
}

func (x *CompletionSourceInfo) GetBuffer() string {
	if x != nil {
		return x.Buffer
	}
	return ""
}

var File_clui_completion_proto protoreflect.FileDescriptor

var file_clui_completion_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6c, 0x75, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6c, 0x75, 0x69, 0x22, 0xaf, 0x01,
	0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x22,
	0xc2, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6c, 0x75, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x19,
	0x0a, 0x08, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x69, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x9c, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x6f, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c,
	0x69, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72,
	0x12, 0x19, 0x0a, 0x08, 0x72, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x72, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x68, 0x61, 0x65, 0x6c, 0x6c, 0x65, 0x65, 0x38, 0x2f, 0x63, 0x6c,
	0x75, 0x69, 0x2d, 0x6e, 0x69, 0x78, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x75, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clui_completion_proto_rawDescOnce sync.Once
	file_clui_completion_proto_rawDescData = file_clui_completion_proto_rawDesc
)

func file_clui_completion_proto_rawDescGZIP() []byte {
	file_clui_completion_proto_rawDescOnce.Do(func() {
		file_clui_completion_proto_rawDescData = protoimpl.X.CompressGZIP(file_clui_completion_proto_rawDescData)
	})
	return file_clui_completion_proto_rawDescData
}

var file_clui_completion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_clui_completion_proto_goTypes = []interface{}{
	(*CompletionEntry)(nil),      // 0: clui.CompletionEntry
	(*CompletionInfo)(nil),       // 1: clui.CompletionInfo
	(*CompletionSourceInfo)(nil), // 2: clui.CompletionSourceInfo
}
var file_clui_completion_proto_depIdxs = []int32{
	0, // 0: clui.CompletionInfo.entries:type_name -> clui.CompletionEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clui_completion_proto_init() }
func file_clui_completion_proto_init() {
	if File_clui_completion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clui_completion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletionEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clui_completion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clui_completion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletionSourceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clui_completion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clui_completion_proto_goTypes,
		DependencyIndexes: file_clui_completion_proto_depIdxs,
		MessageInfos:      file_clui_completion_proto_msgTypes,
	}.Build()
	File_clui_completion_proto = out.File
	file_clui_completion_proto_rawDesc = nil
	file_clui_completion_proto_goTypes = nil
	file_clui_completion_proto_depIdxs = nil
}
