// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: clui/terminal.proto

package clui

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Winsize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows uint32 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols uint32 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	X    uint32 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y    uint32 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Winsize) Reset() {
	*x = Winsize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clui_terminal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Winsize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Winsize) ProtoMessage() {}

func (x *Winsize) ProtoReflect() protoreflect.Message {
	mi := &file_clui_terminal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Winsize.ProtoReflect.Descriptor instead.
func (*Winsize) Descriptor() ([]byte, []int) {
	return file_clui_terminal_proto_rawDescGZIP(), []int{0}
}

func (x *Winsize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Winsize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Winsize) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Winsize) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_clui_terminal_proto protoreflect.FileDescriptor

var file_clui_terminal_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6c, 0x75, 0x69, 0x2f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6c, 0x75, 0x69, 0x22, 0x4d, 0x0a, 0x07, 0x57,
	0x69, 0x6e, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x79, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x68, 0x61, 0x65, 0x6c,
	0x6c, 0x65, 0x65, 0x38, 0x2f, 0x63, 0x6c, 0x75, 0x69, 0x2d, 0x6e, 0x69, 0x78, 0x2f, 0x67, 0x6f,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x75, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clui_terminal_proto_rawDescOnce sync.Once
	file_clui_terminal_proto_rawDescData = file_clui_terminal_proto_rawDesc
)

func file_clui_terminal_proto_rawDescGZIP() []byte {
	file_clui_terminal_proto_rawDescOnce.Do(func() {
		file_clui_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(file_clui_terminal_proto_rawDescData)
	})
	return file_clui_terminal_proto_rawDescData
}

var file_clui_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_clui_terminal_proto_goTypes = []interface{}{
	(*Winsize)(nil), // 0: clui.Winsize
}
var file_clui_terminal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clui_terminal_proto_init() }
func file_clui_terminal_proto_init() {
	if File_clui_terminal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clui_terminal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Winsize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clui_terminal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clui_terminal_proto_goTypes,
		DependencyIndexes: file_clui_terminal_proto_depIdxs,
		MessageInfos:      file_clui_terminal_proto_msgTypes,
	}.Build()
	File_clui_terminal_proto = out.File
	file_clui_terminal_proto_rawDesc = nil
	file_clui_terminal_proto_goTypes = nil
	file_clui_terminal_proto_depIdxs = nil
}
